SET GLOBAL net_buffer_length = 1000000;
SET GLOBAL max_allowed_packet = 1000000000;

USE brasileirao;

INSERT INTO clubes (id_clube, nome, estado)
VALUES
	(NULL, "Vasco", "RJ"),
	(NULL, "Guarani", "SP"),
	(NULL, "Gremio", "RS"),
	(NULL, "Athletico-PR", "PR"),
	(NULL, "Coritiba", "PR"),
	(NULL, "Flamengo", "RJ"),
	(NULL, "Paysandu", "PA"),
	(NULL, "Goias", "GO"),
	(NULL, "Ponte Preta", "SP"),
	(NULL, "Internacional", "RS"),
	(NULL, "Fluminense", "RJ"),
	(NULL, "Criciuma", "SC"),
	(NULL, "Sao Paulo", "SP"),
	(NULL, "Juventude", "RS"),
	(NULL, "Bahia", "BA"),
	(NULL, "Fortaleza", "CE"),
	(NULL, "Sao Caetano", "SP"),
	(NULL, "Cruzeiro", "MG"),
	(NULL, "Figueirense", "SC"),
	(NULL, "Vitoria", "BA"),
	(NULL, "Parana", "PR"),
	(NULL, "Santos", "SP"),
	(NULL, "Atletico-MG", "MG"),
	(NULL, "Corinthians", "SP"),
	(NULL, "Botafogo-RJ", "RJ"),
	(NULL, "Palmeiras", "SP"),
	(NULL, "Brasiliense", "DF"),
	(NULL, "Santa Cruz", "PE"),
	(NULL, "Nautico", "PE"),
	(NULL, "America-RN", "RN"),
	(NULL, "Sport", "PE"),
	(NULL, "Ipatinga", "MG"),
	(NULL, "Portuguesa", "SP"),
	(NULL, "Barueri", "SP"),
	(NULL, "Avai", "SC"),
	(NULL, "Santo Andre", "SP"),
	(NULL, "Atletico-GO", "GO"),
	(NULL, "Ceara", "CE"),
	(NULL, "Gremio Prudente", "SP"),
	(NULL, "America-MG", "MG"),
	(NULL, "Chapecoense", "SC"),
	(NULL, "Joinville", "SC"),
	(NULL, "CSA", "AL"),
	(NULL, "Bragantino", "SP"),
	(NULL, "Cuiaba", "MT");